### ISSUE TITLE
Sideloaded app crashes on launch.

### ISSUE THREAD

**Issue by qnblackcat** [PoomSmart/IAmYouTube#1]
**Specs:**
- iPhone 6s - iOS 14.3 - Substitute
- YouTube 16.28.2 & Cercube 5.2.28 & IAmYouTube
- Sideloaded via AltStore

I tried to combine IAmYouTube and Cercube into one iPA. The app keeps crashing on launch. I can confirm that the app works fine with only Cercube injected. 

Crash log from Cr4shed:
[text-D5F378A63ECE-1.txt](https://github.com/PoomSmart/IAmYouTube/files/6856185/text-D5F378A63ECE-1.txt)

Crash log from iOS:
[YouTube-2021-07-21-203455.txt](https://github.com/PoomSmart/IAmYouTube/files/6856197/YouTube-2021-07-21-203455.txt)

**Comment by PoomSmart** [comment]
Try 1.0.1

**Comment by qnblackcat** [comment]
No more crash on 1.0.1 👍
However, I couldn't see the deep link, aka "Open in the Youtube app" when I visit www.youtube.com from Safari. 
![IMG_1402](https://user-images.githubusercontent.com/52943116/126505144-0f2336b1-36be-40c0-8103-24a8590dfd24.PNG)
