### ISSUE TITLE
Version 1.1.0 crashes the app in jailed mode

### ISSUE THREAD

**Issue by superrnovae** [PoomSmart/IAmYouTube#3]
Here's a full log: 
[YouTube-2021-07-29-213822.txt](https://github.com/PoomSmart/IAmYouTube/files/6903552/YouTube-2021-07-29-213822.txt)
[YouTube-2021-07-29-213822.000.txt](https://github.com/PoomSmart/IAmYouTube/files/6903553/YouTube-2021-07-29-213822.000.txt)

**Comment by PoomSmart** [comment]
@bakedpotato191 So does 1.1.1?

**Comment by superrnovae** [comment]
> @bakedpotato191 So does 1.1.1?

No. 1.1.1 injects perfectly. Can't log into the account when sideloaded with ios-deploy, but with AltStore I don't have such issue, but I keep getting logged out of my account on app restart.

**Comment by PoomSmart** [comment]
The part that IAmYouTube will probably not include is the hook of SSO service as done in sideloaded uYou. It's a different concern.
