### ISSUE TITLE
Cause crash with sideloaded IPA

### ISSUE THREAD

**Issue by CySxL** [PoomSmart/IAmYouTube#4]
Not sure how uYouPlus implements it but every time I tried to inject IAmYouTube to my own YT IPA, the output YT IPA would always crash due to the injection.

**Comment by PoomSmart** [comment]
Crash log?

**Comment by CySxL** [comment]
> Crash log?

here u go:https://pastebin.com/PxWfjgCW



YT app only crashes when I add IAmYouTube to the inject list. If I remove IAmYouTube then everything is fine.

**Comment by PoomSmart** [comment]
Not sure here. Did you try removing `- (id)objectForInfoDictionaryKey:(NSString *)key` hook from it?

**Comment by PoomSmart** [comment]
Should be fixed with the latest commit.
